version: 0.2

phases:
  pre_build:
    commands:
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $ECR_URL
  build:
    command:
      - docker build -t demo_llm . 

      - docker tag demo_llm:lastest $ECR_URL:lastest 

  post_build:
    command:
      - docker push $ECR_URL:lastest 
      
      - printf '[{"name":"llm-chatbot","imageUri":"%s"}]' $ECR_URI:latest > imagedefinitions.json

artifacts:
  files:
    - imagedefinations.json